### ISSUE TITLE
Error in glue

### ISSUE THREAD

**Issue by mlpereira87** [epi2me-labs/wf-alignment#18] opened 2023-11-08 12:39 UTC
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu 20.04

### Workflow Version

last

### Workflow Execution

Command line

### CLI command run

/nextflow run /wf-alignment/main.nf -w /Project_data/work --out_dir /Project_data/outputs --sample Generic --fastq fastq_folder/ --references reference_select/ --depth_coverage true --concat_fastq true --threads $(nproc) --disable_ping true

### Workflow Execution - CLI Execution Profile

None

### What happened?

Traceback (most recent call last):
  File "/home/adminf/data/nextflow_work/wf-alignment/bin/workflow-glue", line 7, in <module>
    cli()
  File "/home/adminf/data/nextflow_work/wf-alignment/bin/workflow_glue/__init__.py", line 72, in cli
    args.func(args)
  File "/home/adminf/data/nextflow_work/wf-alignment/bin/workflow_glue/report.py", line 29, in main
    depth_df = read_data.depths(args.depths_dir, sample_names)
  File "/home/adminf/data/nextflow_work/wf-alignment/bin/workflow_glue/report_utils/read_data.py", line 114, in depths
    (fname,) = [x for x in os.listdir(depths_dir) if x.startswith(sample_name)]

### Relevant log output

```shell
executor >  local (197)
[-        ] process > fastcat                        -
[84/18fe88] process > move_or_compress_fq_file (13)  [100%] 21 of 21 ✔
[9e/610ff0] process > pipeline:getParams             [100%] 1 of 1 ✔
[a9/db9495] process > pipeline:getVersions           [100%] 1 of 1 ✔
[5b/f68dc6] process > pipeline:process_references... [100%] 1 of 1 ✔
[cc/f104f9] process > pipeline:process_references... [100%] 1 of 1 ✔
[8c/87aa0b] process > pipeline:alignReads (21)       [100%] 21 of 21 ✔
[b5/8e2bb2] process > pipeline:indexBam (17)         [100%] 21 of 21 ✔
[d0/4cca90] process > pipeline:bamstats (21)         [100%] 21 of 21 ✔
[5b/2ab563] process > pipeline:addStepsColumn        [100%] 1 of 1 ✔
[07/e8cfab] process > pipeline:readDepthPerRef (21)  [100%] 21 of 21 ✔
[e8/48ccb0] process > pipeline:makeReport            [  0%] 0 of 1
[00/9ca088] process > configure_jbrowse              [100%] 1 of 1 ✔
[c3/63abd9] process > output (77)                    [100%] 85 of 85
Error executing process > 'pipeline:makeReport'

Caused by:
  Process `pipeline:makeReport` terminated with an error exit status (1)

Command executed:

  workflow-glue report         --name wf-alignment         --stats_dir readstats         --flagstat_dir flagstat         --refnames_dir refnames         --versions versions.txt         --params params.json         --depths_dir depths

Command exit status:
  1

Command output:
  (empty)

Command error:
  [12:06:29 - matplotlib.font_manager] generated new fontManager
  [12:06:30 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/home/adminf/data/nextflow_work/wf-alignment/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/adminf/data/nextflow_work/wf-alignment/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/home/adminf/data/nextflow_work/wf-alignment/bin/workflow_glue/report.py", line 29, in main
      depth_df = read_data.depths(args.depths_dir, sample_names)
    File "/home/adminf/data/nextflow_work/wf-alignment/bin/workflow_glue/report_utils/read_data.py", line 114, in depths
      (fname,) = [x for x in os.listdir(depths_dir) if x.startswith(sample_name)]
  ValueError: too many values to unpack (expected 1)

Work dir:
  /home/adminf/data/nextflow_work/Project_data/work/e8/48ccb00ad13e18464ddf6ce852c00b

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

**Comment by mlpereira87** [comment] 2023-11-08 12:57
Solved it with this:

```
def depths(depths_dir, sample_names):
    """Read depth data.

    :param depths_dir: directory with `mosdepth` output files
    :param sample_names: list of sample names for which we found reads
    :return: `pd.DataFrame` with columns `["ref", "start", "end", "depth",
        "sample_name"]`
    """
    dfs = []
    for sample_name in sample_names:
        #(fname,) = [x for x in os.listdir(depths_dir) if x.startswith(sample_name)]
        df = pd.read_csv(
            #f"{depths_dir}/{fname}",
            f"{depths_dir}/{sample_name}.all_regions.bed.gz",
            sep="\t",
            header=None,
            names=["ref", "start", "end", "depth"],
        )
        dfs.append(df.eval(f'sample_name = "{sample_name}"'))
    return pd.concat(dfs).astype({"sample_name": CATEGORICAL, "ref": CATEGORICAL})

```

**Comment by julibeg** [comment] 2023-11-08 13:35
Hi @mlpereira87! Could you please confirm that you are running on the most recent version (v0.6.1)? In your command you use the `--concat_fastq` parameter, which was removed in v0.5.2.

**Comment by mlpereira87** [comment] 2023-11-08 14:44
```
||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-alignment v0.6.1
--------------------------------------------------------------------------------
```

**Comment by julibeg** [comment] 2023-11-08 14:51
Thanks for confirming. Could you please send the structure of your input data (i.e. the output of `tree fastq_folder`).

**Comment by mlpereira87** [comment] 2023-11-08 17:12
```
ls depths/
1-pool-2.all_regions.bed.gz   X1-10e3.all_regions.bed.gz         V10.all_regions.bed.gz                    V11-Pool-2.all_regions.bed.gz       V2.all_regions.bed.gz  V5-Direto.all_regions.bed.gz        V7-Pool-1-Direto-45x.all_regions.bed.gz
2-pool-2.all_regions.bed.gz   neg.all_regions.bed.gz               V11.all_regions.bed.gz                    V1.all_regions.bed.gz               V4.all_regions.bed.gz  V5-WGA-Midi-45x.all_regions.bed.gz  V7-WGA-Midi.all_regions.bed.gz
K2-pool-2.all_regions.bed.gz  S1-Spike-X1-V3.all_regions.bed.gz  V11-Pool-1-Direto-45x.all_regions.bed.gz  V1-WGA-Midi-45x.all_regions.bed.gz  V5.all_regions.bed.gz  V7.all_regions.bed.gz               V8.all_regions.bed.gz
```

**Comment by julibeg** [comment] 2023-11-08 20:29
Thanks! I reproduced the issue. It is caused by some sample names beginning with the name of another sample (e.g. `V7` and `V7-Pool-1-Direto-45x`). It will be fixed in the next release. In the meantime, you could either rename your directories or use a sample sheet to give the samples "unique" aliases. For example, this could look like the below
```
barcode,alias,type
1-pool-2,sample01,test_sample
2-pool-2,sample02,test_sample
K2-pool-2,sample03,test_sample
X1-10e3,sample04,test_sample
neg,sample05,test_sample
S1-Spike-X1-V3,sample06,test_sample
V1,sample07,test_sample
V10,sample08,test_sample
V11,sample09,test_sample
V11-Pool-1-Direto-45x,sample10,test_sample
V11-Pool-2,sample11,test_sample
V1-WGA-Midi-45x,sample12,test_sample
V2,sample13,test_sample
V4,sample14,test_sample
V5,sample15,test_sample
V5-Direto,sample16,test_sample
V5-WGA-Midi-45x,sample17,test_sample
V7,sample18,test_sample
V7-Pool-1-Direto-45x,sample19,test_sample
V7-WGA-Midi,sample20,test_sample
V8,sample21,test_sample
```

**Comment by julibeg** [comment] 2023-11-16 17:25
Hi @mlpereira87, v0.6.2 should have fixed this issue. Could you please update the workflow and try with your original data to confirm that the problem no longer occurs?

**Closed** 2023-11-16 17:26 UTC
