### ISSUE TITLE
Error: mv: cannot stat 'mapula.json': No such file or directory

### ISSUE THREAD

**Issue by stefandiederich** [epi2me-labs/wf-alignment#7] opened 2022-06-22 12:03 UTC
Hi, 

I testet the wf-alignment pipeline with the testdata you provide but get the following error:

```
k-hg-srv3:/media/Data # nextflow run epi2me-labs/wf-alignment --fastq /media/Rohdaten/wf-human-alignment_testdata/test.fastq --references /media/Rohdaten/wf-human-alignment_testdata/
N E X T F L O W  ~  version 22.04.4
Launching `https://github.com/epi2me-labs/wf-alignment` [ecstatic_lavoisier] DSL2 - revision: 6c4c39442f [master]
Core Nextflow options
  revision       : master
  runName        : ecstatic_lavoisier
  containerEngine: docker
  launchDir      : /media/Data
  workDir        : /media/Data/work
  projectDir     : /root/.nextflow/assets/epi2me-labs/wf-alignment
  userName       : root
  profile        : standard
  configFiles    : /root/.nextflow/assets/epi2me-labs/wf-alignment/nextflow.config

Input/output options
  fastq          : /media/Rohdaten/wf-human-alignment_testdata/test.fastq

Reference genome options
  references     : /media/Rohdaten/wf-human-alignment_testdata/

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use epi2me-labs/wf-alignment for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x



Checking fastq input.
executor >  local (12)
[6f/da8fa0] process > start_ping:pingMessage (1)     [100%] 1 of 1 ✔
[4f/acc019] process > handleSingleFile (1)           [100%] 1 of 1 ✔
[a9/97de3b] process > pipeline:fastcatUncompress (1) [100%] 1 of 1 ✔
[91/26d50c] process > pipeline:combineReferences     [100%] 1 of 1 ✔
[15/05a5d7] process > pipeline:alignReads (1)        [  0%] 0 of 1
[-        ] process > pipeline:mergeBAM              -
[-        ] process > pipeline:indexBam              -
[43/95ce07] process > pipeline:refLengths            [100%] 1 of 1 ✔
executor >  local (12)
[6f/da8fa0] process > start_ping:pingMessage (1)     [100%] 1 of 1 ✔
[4f/acc019] process > handleSingleFile (1)           [100%] 1 of 1 ✔
[a9/97de3b] process > pipeline:fastcatUncompress (1) [100%] 1 of 1 ✔
[91/26d50c] process > pipeline:combineReferences     [100%] 1 of 1 ✔
[15/05a5d7] process > pipeline:alignReads (1)        [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:mergeBAM              -
[-        ] process > pipeline:indexBam              -
[43/95ce07] process > pipeline:refLengths            [100%] 1 of 1 ✔
[22/4fb9c2] process > pipeline:addStepsColumn        [100%] 1 of 1 ✔
[-        ] process > pipeline:readDepthPerRef       -
[ec/3a6af5] process > pipeline:getParams             [100%] 1 of 1 ✔
[e5/8b3e4d] process > pipeline:getVersions           [100%] 1 of 1 ✔
[46/efe108] process > pipeline:getRefNames (1)       [100%] 2 of 2 ✔
[-        ] process > pipeline:gatherStats           -
[-        ] process > pipeline:mergeCSV              -
[-        ] process > pipeline:plotStats             -
[-        ] process > output                         -
[5e/e4083e] process > end_ping:pingMessage           [100%] 1 of 1 ✔
Single file input detected.
Error executing process > 'pipeline:alignReads (1)'

Caused by:
  Process `pipeline:alignReads (1)` terminated with an error exit status (1)

Command executed:

  minimap2 -y -t 4 -ax map-ont combined.fasta test.reads.fastq.gz     | mapula count  -r SIRV.fasta ERCC.fasta -s fasta run_id barcode -f json -p     | samtools sort -@ 4 -o test.sorted.aligned.bam -
  mv mapula.json test.mapula.json
  bamtools split -in test.sorted.aligned.bam -mapped
  (bedtools bamtofastq -i *UNMAPPED.bam -fq temp.unmapped.fq     && fastcat -s temp.unmapped.fq -r test.unmapped.stats -x temp.unmapped.fq >> temp.uncompressed.fastq)     || touch test.unmapped.stats
  rm -rf *temp*
  rm -rf *UNMAPPED*

Command exit status:
  1

Command output:
  (empty)

Command error:
  [M::mm_idx_gen::0.017*0.89] collected minimizers
  [M::mm_idx_gen::0.031*2.01] sorted minimizers
  [M::main::0.031*2.01] loaded/built the index for 99 target sequence(s)
  [M::mm_mapopt_update::0.034*1.93] mid_occ = 14
  [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 99
  [M::mm_idx_stat::0.035*1.90] distinct minimizers: 37663 (77.56% are singletons); average occurrences: 1.529; average spacing: 5.311; total length: 305775
  [M::main] Version: 2.24-r1122
  [M::main] CMD: minimap2 -y -t 4 -ax map-ont combined.fasta test.reads.fastq.gz
  [M::main] Real time: 0.040 sec; CPU: 0.072 sec; Peak RSS: 0.008 GB
  Running: Mapula (count)
  [1/3] Loading references
  [2/3] Parsing alignments

  0it [00:00, ?it/s]

  No aggregations made, is the BAM file empty?
  mv: cannot stat 'mapula.json': No such file or directory

Work dir:
  /media/Data/work/15/05a5d7affd25ea5268f77aab9feab5

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

```

Do you have any solution for that error?

Bests
Stefan

**Comment by matteo1313** [comment] 2022-07-15 22:05
Hello , 
I appear to be getting the same error. 

Error executing process > 'pipeline:alignReads (1)'

Caused by:
  Process `pipeline:alignReads (1)` terminated with an error exit status (1)

Command executed:

  minimap2 -y -t 4 -ax map-ont combined.fasta pseudo_combined.reads.fastq.gz     | mapula count  -r PseudoPA0750Genome.fasta -s fasta run_id barcode -f json -p     | samtools sort -@ 4 -o pseudo_combined.sorted.aligned.bam - 
  mv mapula.json pseudo_combined.mapula.json
  bamtools split -in pseudo_combined.sorted.aligned.bam -mapped
  (bedtools bamtofastq -i *UNMAPPED.bam -fq temp.unmapped.fq     && fastcat -s temp.unmapped.fq -r pseudo_combined.unmapped.stats -x temp.unmapped.fq >> temp.uncompressed.fastq)     || touch pseudo_combined.unmapped.stats
  rm -rf *temp*
  rm -rf *UNMAPPED*

Command exit status:
  1

Command output:
  (empty)

Command error:
  [M::mm_idx_gen::0.170*1.01] collected minimizers
  [M::mm_idx_gen::0.216*1.64] sorted minimizers
  [M::main::0.216*1.64] loaded/built the index for 1 target sequence(s)
  [M::mm_mapopt_update::0.240*1.57] mid_occ = 10
  [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
  [M::mm_idx_stat::0.298*1.33] distinct minimizers: 1050404 (92.00% are singletons); average occurrences: 1.109; average spacing: 5.358; total length: 6241875
  [M::main] Version: 2.24-r1122
  [M::main] CMD: minimap2 -y -t 4 -ax map-ont combined.fasta pseudo_combined.reads.fastq.gz
  [M::main] Real time: 0.305 sec; CPU: 0.403 sec; Peak RSS: 0.072 GB
  Running: Mapula (count)
  [1/3] Loading references
  [2/3] Parsing alignments
  
  0it [00:00, ?it/s]
                    
  No aggregations made, is the BAM file empty?
  mv: cannot stat 'mapula.json': No such file or directory

Work dir:
  /home/matteo/work/34/2a514eaf23873edd360e4e3a44bf30

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

I wonder if it is because the reference file isn't the right one?

**Comment by sarahjeeeze** [comment] 2022-08-15 14:51
Hi, I was unable to recreate this error but there have been some updates to the library we use for counting since this so maybe try again with v1.0.8 and let me know if you still get the error.

**Comment by julibeg** [comment] 2023-07-07 15:28
Closing since there was no more response (the workflow also no longer uses `mapula`).

**Comment by julibeg** [comment] 2023-07-07 15:28
Closing since there was no more response (the workflow also no longer uses mapula).

**Closed by julibeg** 2023-07-07 15:28 UTC
